export const nicheConfig = {
  id: "coconala-sns-blog",
  brandName: "ココナラ",
  siteName: "SNS・ブログ外注ガイド",
  shortName: "外注ガイド",
  siteUrl: "https://www.sns-blog-outsourcing-guide.com",
  locale: "ja_JP",
  language: "ja-JP",
  siteDescription:
    "SNS運用者・ブログ運営者向けに、SNSアイコン・似顔絵、ロゴ作成、YouTubeサムネイル、Kindle本表紙、SNSプロフィール文、記事リライトを自作するか外注するか判断できるよう整理するココナラ依頼ガイドです。",
  metaTitle: "SNS・ブログ素材をココナラで依頼する前に読むガイド",
  logoSubtitle: "SNS・ブログ制作の依頼判断メディア",
  hero: {
    eyebrow: "SNS・ブログ運営者のための外注判断ガイド",
    title: "自作で粘るか、ココナラで頼むか。制作の迷いどころを整理する",
    body:
      "SNSアイコン・似顔絵、ロゴ作成、YouTubeサムネイル、Kindle本表紙、SNSプロフィール文、記事リライトなど、発信まわりの制作課題をココナラのカテゴリに沿って整理します。自作で十分な範囲と、外注した方が成果に近い場面を比べて考えられるサイトです。",
    primaryAction: "記事を読む",
    secondaryAction: "依頼カテゴリから探す",
    secondaryHref: "/?category=request#articles",
  },
  disclosure:
    "当サイトはA8.net等のアフィリエイト広告を利用しています。記事内のリンクからサービスを利用すると、運営者に報酬が発生する場合があります。",
  navItems: [
    ["記事一覧", "/#articles"],
    ["画像制作", "/?product=visual#articles"],
    ["文章・編集", "/?product=writing#articles"],
    ["依頼前チェック", "/?category=request#articles"],
    ["失敗回避", "/?category=trouble#articles"],
  ],
  intentCards: [
    ["SNSアイコン・似顔絵", "SNSの顔になるアイコンやイラストを依頼する", "/?product=sns-icon#articles"],
    ["ロゴ作成", "ブログや個人ブランドの印象を決めるロゴを作る", "/?product=blog-logo#articles"],
    ["YouTubeサムネイル", "クリック率に関わる動画サムネイルを外注する", "/?product=youtube-thumbnail#articles"],
    ["Kindle本表紙", "電子書籍の第一印象を整える表紙を依頼する", "/?product=kindle-cover#articles"],
    ["SNSプロフィール文", "自己紹介や導線が伝わる文章に整える", "/?product=profile-copy#articles"],
    ["記事リライト・編集", "既存記事を読みやすく、検索意図に合う形へ直す", "/?product=article-edit#articles"],
  ],
  categoryLabels: {
    request: "依頼前チェック",
    selfmade: "自作の限界",
    compare: "比較・選び方",
    template: "依頼文テンプレ",
    trouble: "失敗回避",
    recommend: "おすすめ用途",
  },
  productLabels: {
    "sns-icon": "SNSアイコン・似顔絵",
    "blog-logo": "ロゴ作成",
    "youtube-thumbnail": "YouTubeサムネイル",
    "kindle-cover": "Kindle本表紙",
    "note-header": "noteヘッダー",
    "profile-copy": "SNSプロフィール文",
    "article-edit": "記事リライト・編集",
    "blog-parts": "ブログ素材・パーツ",
    "canva-support": "Canva外注",
    visual: "画像・デザイン",
    writing: "文章・編集",
  },
  productLinks: [
    ["SNSアイコン・似顔絵", "/?product=sns-icon#articles"],
    ["ロゴ作成", "/?product=blog-logo#articles"],
    ["YouTubeサムネイル", "/?product=youtube-thumbnail#articles"],
    ["Kindle本表紙", "/?product=kindle-cover#articles"],
    ["SNSプロフィール文", "/?product=profile-copy#articles"],
    ["記事リライト・編集", "/?product=article-edit#articles"],
  ],
  troubleLinks: [
    ["制作外注の相場を知りたい", "/?intent=budget#articles"],
    ["依頼文の書き方を知りたい", "/?intent=brief#articles"],
    ["イラスト依頼の相場を知りたい", "/?intent=budget&product=sns-icon#articles"],
    ["ロゴ作成の相場を知りたい", "/?intent=budget&product=blog-logo#articles"],
    ["自作か外注か迷っている", "/?intent=selfmade-limit#articles"],
    ["ココナラ依頼で失敗したくない", "/?intent=creator-selection#articles"],
  ],
  targetOffers: [
    offer({
      id: "sns-icon",
      label: "アイコン作成・SNSイラスト作成",
      product: "sns-icon",
      categoryUrl: "https://coconala.com/categories/191",
      allowedCategory: "イラスト・モデリング・漫画 / アイコン作成・SNSイラスト作成",
      ctaText: "アイコン作成・SNSイラスト作成をココナラで探す",
      seedKeywords: ["SNS アイコン 依頼", "SNS イラスト 作成", "X アイコン 外注"],
    }),
    offer({
      id: "blog-logo",
      label: "ロゴ作成・ロゴデザイン",
      product: "blog-logo",
      categoryUrl: "https://coconala.com/categories/351",
      allowedCategory: "デザイン / ロゴ作成・ロゴデザイン",
      ctaText: "ロゴ作成・ロゴデザインをココナラで探す",
      seedKeywords: ["ブログ ロゴ 依頼", "個人ブログ ロゴ 外注", "ロゴ デザイン 依頼"],
    }),
    offer({
      id: "youtube-thumbnail",
      label: "YouTube・動画サムネイル作成",
      product: "youtube-thumbnail",
      categoryUrl: "https://coconala.com/categories/355/354",
      allowedCategory: "Webサイト制作・Webデザイン / サムネイル作成・画像デザイン",
      ctaText: "YouTube・動画サムネイル作成をココナラで探す",
      seedKeywords: ["YouTube サムネイル 依頼", "YouTube サムネイル 作成", "サムネイル デザイン 外注"],
    }),
    offer({
      id: "kindle-cover",
      label: "Kindle本表紙・本表紙デザイン作成",
      product: "kindle-cover",
      categoryUrl: "https://coconala.com/categories/608/206",
      allowedCategory: "デザイン / 書籍デザイン・表紙作成",
      ctaText: "Kindle本表紙デザインをココナラで探す",
      seedKeywords: ["Kindle 表紙 依頼", "電子書籍 表紙 外注", "Kindle 表紙 デザイン"],
    }),
    offer({
      id: "note-header",
      label: "noteヘッダー制作",
      product: "note-header",
      categoryUrl: "https://coconala.com/categories/22",
      allowedCategory: "Webサイト制作・Webデザイン",
      ctaText: "noteヘッダー制作をココナラで探す",
      seedKeywords: ["note ヘッダー 依頼", "note 見出し画像 作り方", "note アイキャッチ 外注"],
    }),
    offer({
      id: "profile-copy",
      label: "SNSプロフィール文・自己紹介文",
      product: "profile-copy",
      categoryUrl: "https://coconala.com/categories/19",
      allowedCategory: "ライティング・翻訳",
      ctaText: "プロフィール文・自己紹介文の作成をココナラで探す",
      seedKeywords: ["プロフィール文 添削", "自己紹介文 作成 依頼", "SNS プロフィール 文 作成"],
    }),
    offer({
      id: "article-edit",
      label: "記事リライト・文章編集",
      product: "article-edit",
      categoryUrl: "https://coconala.com/categories/371/149",
      allowedCategory: "ライティング・翻訳 / 文章校正・編集・リライト",
      ctaText: "記事リライト・文章編集をココナラで探す",
      seedKeywords: ["記事 リライト 依頼", "記事 文章編集 依頼", "ブログ 記事 添削"],
    }),
    offer({
      id: "blog-parts",
      label: "ブログ素材・パーツ制作",
      product: "blog-parts",
      categoryUrl: "https://coconala.com/categories/22",
      allowedCategory: "Webサイト制作・Webデザイン",
      ctaText: "ブログ素材制作をココナラで探す",
      seedKeywords: ["ブログ パーツ デザイン", "アイキャッチ 依頼", "ブログ バナー 外注"],
    }),
  ],
  keywordPlans: [
    plan("SNS アイコン 依頼", "sns-icon-request", "request", "sns-icon", "brief", "sns-icon"),
    plan("X アイコン 外注", "x-icon-outsourcing", "compare", "sns-icon", "creator-selection", "sns-icon"),
    plan("ブログ ロゴ 作り方", "blog-logo-selfmade", "selfmade", "blog-logo", "selfmade-limit", "blog-logo"),
    plan("ブログ ロゴ 依頼", "blog-logo-request", "request", "blog-logo", "brief", "blog-logo"),
    plan("YouTube サムネイル 依頼", "youtube-thumbnail-request", "request", "youtube-thumbnail", "creator-selection", "youtube-thumbnail"),
    plan("Kindle 表紙 依頼", "kindle-cover-request", "request", "kindle-cover", "budget", "kindle-cover"),
    plan("note ヘッダー 作り方", "note-header-selfmade", "selfmade", "note-header", "selfmade-limit", "note-header"),
    plan("プロフィール文 添削", "profile-copy-edit", "template", "profile-copy", "brief", "profile-copy"),
    plan("記事 リライト 依頼", "article-rewrite-request", "request", "article-edit", "brief", "article-edit"),
    plan("Canva 限界 外注", "canva-limit-outsourcing", "selfmade", "canva-support", "selfmade-limit", "blog-parts"),
  ],
  rakkoSeedKeywords: [
    "SNS アイコン 依頼",
    "ブログ ロゴ 依頼",
    "YouTube サムネイル 依頼",
    "Kindle 表紙 依頼",
    "プロフィール文 添削",
    "記事 リライト 依頼",
  ],
  affiliate: {
    storeName: "ココナラ",
    sidebarKicker: "ココナラ制作依頼",
    sidebarHeading: "目的に近い制作カテゴリから依頼先を探す",
    buttonText: "ココナラで依頼先を探す",
    fallbackUrlEnv: "COCONALA_AFFILIATE_URL",
    fallbackUrl: "https://px.a8.net/svt/ejp?a8mat=4B3HQN+J1W4Y+2PEO+1ID38X",
    inlineText:
      "候補を見比べるなら、記事テーマに近いココナラのサービスで実績、価格、納期、評価を確認しておくと判断しやすくなります。",
    troubleInlineText:
      "依頼で失敗したくない場合は、出品者の実績だけでなく、修正範囲、納品形式、相談時の返信内容まで確認してから進めるのがおすすめです。",
  },
  generation: {
    editorRole:
      "あなたはSNS運用者・ブログ運営者向けに、制作外注の判断を助ける日本語アフィリエイトメディアの編集者です。",
    articleGoal:
      "検索ユーザーが自作すべきか、ココナラで依頼すべきかを判断でき、自然に該当カテゴリやサービス確認へ進める記事本文を作ってください。",
    fallbackProductName: "制作依頼",
    defaultCategory: "依頼前チェック",
    imagePrompt:
      "Create a realistic editorial hero image for a Japanese creator outsourcing guide. Show a tidy desk with a laptop, sketch notebook, smartphone social profile mockup without readable text, color swatches, and design drafts. No visible logos, no readable text, no people posing to camera. Natural daylight, modern but practical mood, high detail, landscape composition.",
    sourceName: "ココナラ公式カテゴリ",
    noSourceMessage:
      "この記事では、価格やサービス内容を断定せず、依頼前にココナラ上の最新情報を確認する前提で整理しています。",
  },
  officialSources: {
    enabled: false,
    sourceSite: "Coconala",
    apiBase: null,
    cachePrefix: "cms/coconala-sources",
    userAgent: "CoconalaSnsBlogGuideBot/0.1 (+https://sns-blog-outsourcing-guide.vercel.app)",
    cacheHoursEnv: "OFFICIAL_SOURCE_CACHE_HOURS",
  },
};

function offer({ id, label, product, categoryUrl, allowedCategory, ctaText, seedKeywords }) {
  return { id, label, product, categoryUrl, allowedCategory, ctaText, seedKeywords };
}

function plan(keyword, slugBase, category, product, intent, offerId = product) {
  return { keyword, slugBase, category, product, intent, offerId };
}
